# These are supported funding model platforms

github: [your-username] # Replace with your GitHub username
patreon: your-patreon-username # Replace with your Patreon username
open_collective: your-open-collective-username # Replace with your Open Collective username
ko_fi: your-ko-fi-username # Replace with your Ko-fi username
tidelift: your-tidelift-username # Replace with your Tidelift username
community_bridge: your-community-bridge-username # Replace with your Community Bridge username
liberapay: your-liberapay-username # Replace with your Liberapay username
issuehunt: your-issuehunt-username # Replace with your IssueHunt username
otechie: your-otechie-username # Replace with your Otechie username
custom: ["https://your-custom-funding-url.com"] # Replace with your custom funding URL