# Release Drafter Configuration
# https://github.com/release-drafter/release-drafter

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '⚡ Performance'
    labels:
      - 'performance'
      - 'perf'
  - title: '🔒 Security'
    labels:
      - 'security'
  - title: '🧪 Testing'
    labels:
      - 'test'
      - 'testing'
  - title: '🏗️ Build'
    labels:
      - 'build'
      - 'ci'
      - 'cd'

template: |
  ## What's Changed

  $CHANGES

  ## 🔗 Links

  - [Documentation](https://github.com/your-username/poker-app/wiki)
  - [Issues](https://github.com/your-username/poker-app/issues)
  - [Discussions](https://github.com/your-username/poker-app/discussions)

  ## 📦 Installation

  ```bash
  npm install poker-app@latest
  ```

  ## 🚀 Quick Start

  ```bash
  # Clone the repository
  git clone https://github.com/your-username/poker-app.git
  cd poker-app

  # Install dependencies
  npm install

  # Start development server
  npm run dev
  ```

  ## 🤝 Contributing

  We welcome contributions! Please see our [Contributing Guidelines](CONTRIBUTING.md) for details.

  ## 📄 License

  This project is licensed under the MIT License - see the [LICENSE](LICENSE) file for details.

  ---

  **Full Changelog**: https://github.com/your-username/poker-app/compare/$PREVIOUS_TAG...$RESOLVED_VERSION

  **GitHub Release**: https://github.com/your-username/poker-app/releases/tag/$RESOLVED_VERSION

  **Download**: https://github.com/your-username/poker-app/archive/refs/tags/$RESOLVED_VERSION.zip

  ---

  *This release was automatically generated by [Release Drafter](https://github.com/release-drafter/release-drafter)*

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

include-labels:
  - 'enhancement'
  - 'bug'
  - 'documentation'
  - 'performance'
  - 'security'
  - 'testing'
  - 'build'
  - 'chore'
  - 'dependencies'

exclude-labels:
  - 'duplicate'
  - 'invalid'
  - 'wontfix'
  - 'question'

no-changes-template: |
  ## What's Changed

  No changes in this release.

  ## 🔗 Links

  - [Documentation](https://github.com/your-username/poker-app/wiki)
  - [Issues](https://github.com/your-username/poker-app/issues)
  - [Discussions](https://github.com/your-username/poker-app/discussions)

  ## 📦 Installation

  ```bash
  npm install poker-app@latest
  ```

  ## 🚀 Quick Start

  ```bash
  # Clone the repository
  git clone https://github.com/your-username/poker-app.git
  cd poker-app

  # Install dependencies
  npm install

  # Start development server
  npm run dev
  ```

  ## 🤝 Contributing

  We welcome contributions! Please see our [Contributing Guidelines](CONTRIBUTING.md) for details.

  ## 📄 License

  This project is licensed under the MIT License - see the [LICENSE](LICENSE) file for details.

  ---

  **Full Changelog**: https://github.com/your-username/poker-app/compare/$PREVIOUS_TAG...$RESOLVED_VERSION

  **GitHub Release**: https://github.com/your-username/poker-app/releases/tag/$RESOLVED_VERSION

  **Download**: https://github.com/your-username/poker-app/archive/refs/tags/$RESOLVED_VERSION.zip

  ---

  *This release was automatically generated by [Release Drafter](https://github.com/release-drafter/release-drafter)*

authors:
  - login: 'your-username'
    name: 'Your Name'
    email: 'your-email@example.com'
    url: 'https://github.com/your-username'

sort: asc